import type { Metadata } from "next";
import { figtree } from "@/app/ui/fonts";
import "@/app/ui/global.css";
import localfont from 'next/font/local';

// export const cwc = localfont({
//   src: "./CWC-Bold.otf",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.className} antialiased`}>{children}</body>
    </html>
  );
}
